app/lk/__init__.py
from flask import Blueprint

bp = Blueprint('lk', __name__, template_folder='templates', static_folder='static')


from app.lk import routes

app/lk/routes.py
from flask import render_template, redirect, flash, url_for, request, current_app, abort
from flask_login import current_user, login_required
from app.lk import bp

from app.main.forms import EmptyForm
from app.auth.models import User
from app.main.models import Query_db


@bp.route('/', methods=['GET'])
@login_required
def lk_home():
    return render_template("lk/index.html")

@bp.route('/messages', methods=['GET'])
@login_required
def messages():
    return render_template("lk/messages.html")


@bp.route('/user/<username>')
@login_required
def user(username):
    user = User().get(login=username)    
    form = EmptyForm()
    return render_template('lk/user.html', user=user, form=form)


@bp.route('/update/<username>', methods=['POST'])
@login_required
def update(username):
    form = EmptyForm()
    if form.validate_on_submit():
        user = User().get(login=username)
        if user is None:
            flash(f'User {username} not found.')
            return redirect(url_for('main.index'))
        if user != current_user:
            flash('You cannot update not yourself!')
            return redirect(url_for('lk.user', username=current_user.login))
        user.update_when_login_user(ip=request.environ['REMOTE_ADDR'])
        flash(f'You are update {username}!')
        return redirect(url_for('lk.user', username=username))
    else:
        return redirect(url_for('lk.index'))
    
@bp.route('/payments', methods=['GET'])
@login_required
def payments():
    user_id = current_user.id
    columns = Query_db().get_user_payments(user_id=user_id, get_columns=True)
    if columns == 404:
        return abort(404)
    
    return render_template('lk/payments.html', 
                           data_url = f'/admin/get_user_payments_data/{user_id}', 
                           limit_row = 15,
                           method = 'POST',
                           columns = columns,
                           header=f'История платежей'
                           )
    
@bp.route('/orders', methods=['GET'])
@login_required
def orders():
    user_id = current_user.id
    columns = Query_db().get_user_orders(user_id=user_id, get_columns=True)
    if columns == 404:
        return abort(404)
    
    return render_template('lk/orders.html', 
                           data_url = f'/admin/get_user_orders_data/{user_id}', 
                           limit_row = 15,
                           method = 'POST',
                           columns = columns,
                           header=f'История заказов'
                           )

app/lk/templates/lk/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Личный кабинет</h1>
    <img src="{{ url_for('lk.static', filename='img/admin.jpg') }}" />
   
{% endblock %}

app/lk/templates/lk/messages.html
{% extends "base.html" %}

{% block content %}
    <h1>Сообщения</h1>
{% endblock %}

app/lk/templates/lk/orders.html
{% extends "base_table.html" %}

{% block content_message %}
<div class="row">
    <div class="col alert alert-info alert-dismissible" role="alert">
        <p>Внимание! Если вы не пользуетесь парсером более 3 месяцев, то история объявлений, которые вы парсили, очистится автоматически.
        <br>Неоплаченные заказы удаляются через 24 часа. Файлы с данными хранятся 7 дней.</p>
    </div>
</div>
{% endblock %}

app/lk/templates/lk/payments.html
{% extends "base_table.html" %}

{% block content_top %}
<!--div class="row">
    <div class="col alert alert-info alert-dismissible" id="msg_balance" role="alert">
        На вашем счету {{current_user.balance}} ₽
    </div>
</div-->
{% endblock %}

app/lk/templates/lk/user.html
{% extends "base.html" %}

{% block content %}
    <table>
        <tr valign="top">
            <td><img src="{{ user.avatar(128) }}"></td>
            <td>
                <h1>User: {{ user.username }}</h1>
                {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
                {% if user.date_last %}<p>Last seen on: {{ user.date_last }}</p>{% endif %}
                {% if user.balance %}<p>На счету: {{ user.balance }} руб.</p>{% endif %}
                {% if user == current_user %}
                <p>
                    <form action="{{ url_for('lk.update', username=user.username) }}" method="post">
                        {{ form.hidden_tag() }}
                        {{ form.submit(value='Update') }}
                    </form>
                </p>
                {% endif %}
            </td>
        </tr>
    </table>
    <hr>
{% endblock %}